# Generated by Django 4.2.16 on 2024-10-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_hotel_hotel_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='created_date',
            new_name='date',
        ),
    ]
