# Generated by Django 4.2.16 on 2024-10-28 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_created_date_rating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelphotos',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_image', to='store.hotel'),
        ),
        migrations.AlterField(
            model_name='roomphotos',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_photos', to='store.room'),
        ),
    ]
